### ISSUE TITLE
QUESTION ❓: Any reason to not include 'OnEnable' and 'OnDisable' on the list of Unity Lifecycle Callbacks?

### ISSUE THREAD

**Issue by niscolas** [GiovanniZambiasi/gameplay-framework-unity#1]

**Comment by niscolas** [comment]
Besides that I'm looking forward in contributing to this project!
Do you plan to maintain / continue developing it?

**Comment by GiovanniZambiasi** [comment]
@niscolas Thank you for your interest!

`OnDisable` and `OnEnable` are callbacks for when a behaviour gets disabled or enabled, and can be called multiple times over the lifetime of a particular object. That's why, though they *can* be called during the creation and destruction of `GameObjects`, I wouldn't consider them *primarily* lifecycle callbacks. If the developer is using them as work-arounds for the "no lifecycle callbacks rule", then that would be considered a rule break.

I also don't want to restrict usage of these callbacks, as they can be useful for other things (such as a pooling system or general optimizations).

> Besides that I'm looking forward in contributing to this project!
Do you plan to maintain / continue developing it?  

Yes! I do have some plans for this package, and hope to polish it as It gets applied to other projects. Feel free to contribute with pull requests!
